/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proto4j_msdp_UUID */

#ifndef _Included_org_proto4j_msdp_UUID
#define _Included_org_proto4j_msdp_UUID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_proto4j_msdp_UUID
 * Method:    newUUID
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_proto4j_msdp_UUID_newUUID
  (JNIEnv *, jobject);

/*
 * Class:     org_proto4j_msdp_UUID
 * Method:    fillUUID
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proto4j_msdp_UUID_fillUUID___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_UUID
 * Method:    fillUUID
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proto4j_msdp_UUID_fillUUID___3B_3B
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
