/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_proto4j_msdp_Packet */

#ifndef _Included_org_proto4j_msdp_Packet
#define _Included_org_proto4j_msdp_Packet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    createPacket
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_proto4j_msdp_Packet_createPacket
  (JNIEnv *, jobject);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    setPacketType
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proto4j_msdp_Packet_setPacketType
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    setPacketUUID
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proto4j_msdp_Packet_setPacketUUID
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    setPayload
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_proto4j_msdp_Packet_setPayload
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    finishPacket
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_proto4j_msdp_Packet_finishPacket
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketType
 * Signature: ([B)B
 */
JNIEXPORT jbyte JNICALL Java_org_proto4j_msdp_Packet_getPacketType
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketSystemID
 * Signature: ([B)B
 */
JNIEXPORT jbyte JNICALL Java_org_proto4j_msdp_Packet_getPacketSystemID
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketVersion
 * Signature: ([B)S
 */
JNIEXPORT jshort JNICALL Java_org_proto4j_msdp_Packet_getPacketVersion
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketUUID
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_proto4j_msdp_Packet_getPacketUUID
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketChecksum
 * Signature: ([B)S
 */
JNIEXPORT jshort JNICALL Java_org_proto4j_msdp_Packet_getPacketChecksum
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketDataLength
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_proto4j_msdp_Packet_getPacketDataLength
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_proto4j_msdp_Packet
 * Method:    getPacketPayload
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_proto4j_msdp_Packet_getPacketPayload
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
